name: field_array_picker

version: 0.1.0

dependencies:
  uuid: ^2.0.4
  intl: ^0.16.1
  flutter_picker: ^1.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.5.0 <3.0.0"